### ISSUE TITLE
Graphite Basic Auth - Username and Password

### ISSUE THREAD

**Issue by mobilemike** [livingsocial/rearview#1]
I can find no direct documentation, and I'm not well versed in Scala, but t looks like the Graphite.auth config only takes a password. Is there a way to auth against a Graphite server using both username and password? I've tried passing "user:password" but this does not work.

Thanks!

**Comment by talbright** [comment]
Can you try to set the auth string in https://github.com/livingsocial/rearview/blob/master/conf/common.conf#L110 using the following rules:

http://en.wikipedia.org/wiki/Basic_access_authentication#Client_side

It is a bit of a pain to have to base64 encode it yourself by hand, but this should work.

**Comment by pauldegoes** [comment]
Another option would be to add your password to the common.conf graphite.auth entry and to do the encoding in Scala in the Global object:

https://github.com/livingsocial/rearview/blob/master/app/rearview/Global.scala#L41

something like:

lazy val graphiteAuth         = config.getString("graphite.auth").map {auth => new sun.misc.BASE64Encoder().encode(auth.getBytes)}.getOrElse(exitMsg("graphite.auth must be defined in configuration"))

Which would take the auth string: "paul:comanche" and turn it into cGF1bDpjb21hbmNoZQ==
