### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ulises** [livingsocial/rearview#10]
Under which license has this been released?

Thanks!

**Comment by talbright** [comment]
I assume its the same license we've been using with our other projects (MIT). I'm going to verify that and then push a license file to the repo once I do.

**Comment by ulises** [comment]
Marvellous, thanks!

**Comment by talbright** [comment]
Still haven't heard back from legal yet, I'll ping them again today.

**Comment by ulises** [comment]
Thanks for the update Trent!

**Comment by talbright** [comment]
Ok I was right -- its MIT (see PR #11)

**Comment by ulises** [comment]
Brilliant. Thanks for the diligence.

**Comment by talbright** [comment]
Your welcome =D
