### ISSUE TITLE
Database exception when creating user.

### ISSUE THREAD

**Issue by usmanismail** [livingsocial/rearview#14]
Failed to store user
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'created' cannot be null
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.6.0_27]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.6.0_27]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.6.0_27]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:534) ~[na:1.6.0_27]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:411) ~[mysql-connector-java-5.1.21.jar:na]
        at com.mysql.jdbc.Util.getInstance(Util.java:386) ~[mysql-connector-java-5.1.21.jar:na]

**Comment by talbright** [comment]
How was it you were trying to create the user, manually? Or was this an exception that occurred during ~~authorization~~ authentication?

**Comment by usmanismail** [comment]
I was signing in using Open ID with my google apps domain account.

—Usman

**Comment by talbright** [comment]
Can you double check your mysql schema for me. You should see this as the DDL for that column:

```
`created` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00'
```

**Comment by usmanismail** [comment]
See below.

DESCRIBE users;
+------------+--------------+------+-----+---------------------+-----------------------------+
| Field      | Type         | Null | Key | Default             | Extra
                  |
+------------+--------------+------+-----+---------------------+-----------------------------+
| id         | bigint(20)   | NO   | PRI | NULL                |
auto_increment              |
| created    | timestamp    | NO   |     | 0000-00-00 00:00:00 |
                  |
| modified   | timestamp    | NO   |     | CURRENT_TIMESTAMP   | on update
CURRENT_TIMESTAMP |
| email      | varchar(255) | NO   | UNI | NULL                |
                  |
| first_name | varchar(255) | NO   |     | NULL                |
                  |
| last_name  | varchar(255) | NO   |     | NULL                |
                  |
| last_login | timestamp    | YES  |     | NULL                |
                  |
+------------+--------------+------+-----+---------------------+-----------------------------+

**Comment by usmanismail** [comment]
I am on mysql 5.6.13, could be an issue with the mysql version?

**Comment by talbright** [comment]
I'm targeting the end of the week for a new release of rearview (rewritten in ruby), so it may be more efficient to just wait for that.

**Comment by talbright** [comment]
I'm still working out some kinks over the holidays, but you can see the progress here: https://github.com/livingsocial/rearview/tree/ruby-port
