### ISSUE TITLE
java.lang.ClassNotFoundException: javax/crypto/JceSecurity

### ISSUE THREAD

**Issue by khash** [livingsocial/rearview#17]
The database setup step of bin/setup from a clean rvm gemset and jruby 1.7.5 throws the following exception:

<pre>
D, [2014-01-12T11:43:47.120000 #44332] DEBUG -- : Shutdown completed cleanly
LoadError: load error: /Users/khash/work/readview/config/environment -- java.lang.ClassNotFoundException: javax/crypto/JceSecurity
               require at org/jruby/RubyKernel.java:1082
               require at /Users/khash/.rvm/rubies/jruby-1.7.5/lib/ruby/gems/shared/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229
       load_dependency at /Users/khash/.rvm/rubies/jruby-1.7.5/lib/ruby/gems/shared/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:214
               require at /Users/khash/.rvm/rubies/jruby-1.7.5/lib/ruby/gems/shared/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229
  require_environment! at /Users/khash/.rvm/rubies/jruby-1.7.5/lib/ruby/gems/shared/gems/railties-4.0.2/lib/rails/application.rb:189
                (root) at /Users/khash/.rvm/rubies/jruby-1.7.5/lib/ruby/gems/shared/gems/railties-4.0.2/lib/rails/commands.rb:44
               require at org/jruby/RubyKernel.java:1082
                (root) at bin/rails:12
</pre>

**Comment by talbright** [comment]
Ok this explains the other issue #16 you opened. If the bin/setup script fails the initializer won't get copied over.

Are you running java 6 or java 7? 
    java -version

You'll need to install unlimited strength cryptography in the JVM, corresponding to your java version:

http://www.oracle.com/technetwork/java/javase/downloads/jce-6-download-429243.html
http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html

The installation instructions should be included in the zip file.

(for more details you can go here: https://github.com/jruby/jruby/wiki/UnlimitedStrengthCrypto)

**Comment by talbright** [comment]
Did you get this working? If so I'd like to close this out.
