### ISSUE TITLE
Rearview:Engine error during bin/setup

### ISSUE THREAD

**Issue by atulkhaire** [livingsocial/rearview#18]
Hi,

I followed all the steps as per https://github.com/livingsocial/rearview. after running setup script in the bin directory I encountered following error.

rake aborted!
uninitialized constant Rearview::Engine
/home/ubuntu/rearview/config/routes.rb:2:in `block in <top (required)>'
/home/ubuntu/rearview/config/routes.rb:1:in`<top (required)>'
/home/ubuntu/rearview/config/environment.rb:5:in `<top (required)>'

Kindly help me with this issue.

**Comment by talbright** [comment]
Rake isn't invoked until later on in the setup script.

Can you include the complete output from running bin/setup?

**Comment by atulkhaire** [comment]
Hi, here's the complete output.

rearview_production already exists
rake aborted!
uninitialized constant Rearview::Engine
/home/ubuntu/rearview/config/routes.rb:2:in `block in <top (required)>'
/home/ubuntu/rearview/config/routes.rb:1:in`<top (required)>'
/home/ubuntu/rearview/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
/home/ubuntu/rearview/config/routes.rb:2:in`block in <top (required)>': uninitialized constant Rearview::Engine (NameError)
        from /usr/local/lib/ruby/gems/1.9.1/gems/actionpack-4.0.2/lib/action_dispatch/routing/route_set.rb:341:in `instance_exec'
        from /usr/local/lib/ruby/gems/1.9.1/gems/actionpack-4.0.2/lib/action_dispatch/routing/route_set.rb:341:in`eval_block'
        from /usr/local/lib/ruby/gems/1.9.1/gems/actionpack-4.0.2/lib/action_dispatch/routing/route_set.rb:319:in `draw'
        from /home/ubuntu/rearview/config/routes.rb:1:in`<top (required)>'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:40:in`each'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:40:in `load_paths'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:16:in`reload!'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:26:in `block in updater'
        from /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-4.0.2/lib/active_support/file_update_checker.rb:75:in`call'
        from /usr/local/lib/ruby/gems/1.9.1/gems/activesupport-4.0.2/lib/active_support/file_update_checker.rb:75:in `execute'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:27:in`updater'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-4.0.2/lib/rails/application/routes_reloader.rb:6:in `execute_if_updated'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-4.0.2/lib/rails/application/finisher.rb:69:in`block in module:Finisher'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-4.0.2/lib/rails/initializable.rb:30:in `instance_exec'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-4.0.2/lib/rails/initializable.rb:30:in`run'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-4.0.2/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/local/lib/ruby/1.9.1/tsort.rb:150:in`block in tsort_each'
        from /usr/local/lib/ruby/1.9.1/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/lib/ruby/1.9.1/tsort.rb:219:in`each_strongly_connected_component_from'
        from /usr/local/lib/ruby/1.9.1/tsort.rb:182:in `block in each_strongly_connected_component'
        from /usr/local/lib/ruby/1.9.1/tsort.rb:180:in`each'
        from /usr/local/lib/ruby/1.9.1/tsort.rb:180:in `each_strongly_connected_component'
        from /usr/local/lib/ruby/1.9.1/tsort.rb:148:in`tsort_each'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-4.0.2/lib/rails/initializable.rb:54:in `run_initializers'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-4.0.2/lib/rails/application.rb:215:in`initialize!'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-4.0.2/lib/rails/railtie/configurable.rb:30:in `method_missing'
        from /home/ubuntu/rearview/config/environment.rb:5:in`<top (required)>'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-4.0.2/lib/rails/application.rb:189:in `require_environment!'
        from /usr/local/lib/ruby/gems/1.9.1/gems/railties-4.0.2/lib/rails/commands.rb:44:in`<top (required)>'
        from bin/rails:12:in `require'
        from bin/rails:12:in`<main>'

Thanks.

**Comment by talbright** [comment]
Are you using Jruby? That looks like MRI to me

**Comment by atulkhaire** [comment]
Yes, I am using Jruby 1.5.6

**Comment by talbright** [comment]
I think I'm going to have a hard time figuring out exactly what's going on with your environment. But it does seem like jruby is not being invoked, or bundle install is failing. However I can give you a few tips.

First of all you should make sure the script, and anything rearview is running under jruby. In a development or testing mode you would probably want to install either rbenv or rvm (and in fact you can use them for your production deployment as well if you want, it so happens that we do not). If you are not using rbenv or rvm make sure that jruby is first in your PATH. If jruby is setup right it should look something like this, noting that the ruby command is just a link to jruby:

```
$ which ruby
/Users/trentalbrigh/.rvm/rubies/jruby-1.7.5/bin/ruby
$ ls -l /Users/trentalbrigh/.rvm/rubies/jruby-1.7.5/bin/ruby
lrwxr-xr-x  1 trentalbrigh  staff  53 Oct  9 17:24 /Users/trentalbrigh/.rvm/rubies/jruby-1.7.5/bin/ruby@ -> /User /trentalbrigh/.rvm/rubies/jruby-1.7.5/bin/jruby
```

Run these commands from the root of the rearview project and let me know the complete output:

```
$ which ruby
$ ruby -v
$ gem install bundler --no-rdoc --no-ri
$ bundle install
```

Also I would recommend upgrading to Jruby 1.7.5+

**Comment by atulkhaire** [comment]
After running those 4 commands this is what I got

root@ip-172-31-40-165:~/rearview# which ruby
/usr/local/bin/ruby
root@ip-172-31-40-165:~/rearview# ruby -v
ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-linux]
root@ip-172-31-40-165:~/rearview# gem install bundler --no-rdoc --no-ri
Successfully installed bundler-1.5.2
1 gem installed
root@ip-172-31-40-165:~/rearview# bundle install
Using rake 10.1.1
Using i18n 0.6.9
Using minitest 4.7.5
Using multi_json 1.8.2
Using atomic 1.1.14
Using thread_safe 0.1.3
Using tzinfo 0.3.38
Using activesupport 4.0.2
Using builder 3.1.4
Using erubis 2.7.0
Using rack 1.5.2
Using rack-test 0.6.2
Using actionpack 4.0.2
Using mime-types 1.25.1
Using polyglot 0.3.3
Using treetop 1.4.15
Using mail 2.5.4
Using actionmailer 4.0.2
Using activemodel 4.0.2
Using activerecord-deprecated_finders 1.0.3
Using arel 4.0.1
Using activerecord 4.0.2
Using bcrypt-ruby 3.1.2
Using coderay 1.1.0
Using coffee-script-source 1.6.3
Using execjs 2.0.2
Using coffee-script 2.2.0
Using thor 0.18.1
Using railties 4.0.2
Using coffee-rails 4.0.1
Using orm_adapter 0.5.0
Using warden 1.2.3
Using devise 3.2.2
Using diff-lcs 1.2.5
Using dotenv 0.9.0
Using multipart-post 1.2.0
Using faraday 0.8.8
Using foreman 0.63.0
Using hashie 2.0.5
Using hike 1.2.3
Using httpauth 0.2.0
Using jbuilder 1.5.3
Using jquery-rails 3.0.4
Using json 1.8.1
Using jwt 0.1.8
Using method_source 0.8.2
Using mysql 2.9.1
Using oauth2 0.8.1
Using omniauth 1.1.4
Using omniauth-oauth2 1.1.1
Using omniauth-google-oauth2 0.2.1
Using slop 3.4.7
Using pry 0.9.12.4
Using puma 2.7.1
Using bundler 1.6.0.pre.1
Using tilt 1.4.1
Using sprockets 2.10.1
Using sprockets-rails 2.0.1
Using rails 4.0.2
Using rdoc 3.12.2
Using rspec-core 2.14.7
Using rspec-expectations 2.14.4
Using rspec-mocks 2.14.4
Using rspec-rails 2.14.0
Using sass 3.2.13
Using sass-rails 4.0.1
Using sdoc 0.3.20
Using therubyrhino_jar 1.7.4
Using therubyrhino 2.0.2
Using turbolinks 2.1.0
Using uglifier 2.4.0
Updating files in vendor/cache
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.

**Comment by talbright** [comment]
You aren't using jruby when those commands are being invoked; you would get something similar to below if you were:

```
$ ruby -v
jruby 1.7.5 (1.9.3p392) 2013-10-07 74e9291 on Java HotSpot(TM) 64-Bit Server VM 1.7.0_25-b15 [darwin-x86_64]
```

**Comment by atulkhaire** [comment]
Hi Trent,

Sorry to bother you again.
I made sure it uses jruby 1.7.5 now. But still there is some problem.

After executing bin/setup:

1) bundle install completes successfully.
2) Setting up sandbox also completes successfully.

but gets this error during setting up database:

Setting up databases...
LoadError: no such file to load -- /config/boot
           require at org/jruby/RubyKernel.java:1082
           require at /usr/local/rvm/rubies/jruby-1.7.5/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
  require_relative at file:/usr/local/rvm/rubies/jruby-1.7.5/lib/jruby.jar!/jruby/kernel19/kernel.rb:21
            (root) at /bin/rake:2
LoadError: no such file to load -- /config/boot
           require at org/jruby/RubyKernel.java:1082
           require at /usr/local/rvm/rubies/jruby-1.7.5/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
  require_relative at file:/usr/local/rvm/rubies/jruby-1.7.5/lib/jruby.jar!/jruby/kernel19/kernel.rb:21
            (root) at /bin/rails:11

I am using MySQL database, but I assume this error is not related to that.

**Comment by talbright** [comment]
What's the output from running the following at the project root:

```
$ bin/rails server -e production
```

What's the output for this command:

```
$ gem list
```

**Comment by atulkhaire** [comment]
1) output for $ bin/rails server -e production:

=> Booting Puma
=> Rails 4.0.2 application starting in production on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma 2.7.1 starting...
- Min threads: 0, max threads: 16
- Environment: production
- Listening on tcp://0.0.0.0:3000

2) output for gem list:

**\* LOCAL GEMS ***

actionmailer (4.0.2)
actionpack (4.0.2)
activemodel (4.0.2)
activerecord (4.0.2)
activerecord-deprecated_finders (1.0.3)
activerecord-jdbc-adapter (1.3.4)
activerecord-jdbcmysql-adapter (1.3.4)
activesupport (4.0.2)
ancestry (2.0.0)
arel (4.0.1)
atomic (1.1.14 java)
bcrypt-ruby (3.1.2 java)
bouncy-castle-java (1.5.0147)
broach (0.3.0)
builder (3.1.4)
bundler (1.5.2)
bundler-unload (1.0.2)
celluloid (0.14.1)
coderay (1.1.0)
coffee-rails (4.0.1)
coffee-script (2.2.0)
coffee-script-source (1.6.3)
devise (3.2.2)
diff-lcs (1.2.5)
dotenv (0.9.0)
erubis (2.7.0)
execjs (2.0.2)
executable-hooks (1.3.1)
faraday (0.8.8)
ffi (1.9.3 java)
foreman (0.63.0 java)
gem-wrappers (1.2.4)
hashie (2.0.5)
hike (1.2.3)
hitimes (1.2.1 java)
httparty (0.12.0)
httpauth (0.2.0)
i18n (0.6.9)
jbuilder (1.5.3)
jdbc-mysql (5.1.27)
jquery-rails (3.0.4)
jruby-launcher (1.0.19 java)
jruby-openssl (0.9.4)
json (1.8.1 java)
jwt (0.1.8)
mail (2.5.4)
method_source (0.8.2)
mime-types (1.25.1)
minitest (4.7.5)
multi_json (1.8.2)
multi_xml (0.5.5)
multipart-post (1.2.0)
nap (0.6.0)
oauth2 (0.8.1)
omniauth (1.1.4)
omniauth-google-oauth2 (0.2.1)
omniauth-oauth2 (1.1.1)
orm_adapter (0.5.0)
polyglot (0.3.3)
protected_attributes (1.0.5)
pry (0.9.12.4 java)
puma (2.7.1 java)
rack (1.5.2)
rack-test (0.6.2)
rails (4.0.2)
railties (4.0.2)
rake (10.1.1)
rdoc (3.12.2)
rearview (1.0.2 jruby)
rspec-core (2.14.7)
rspec-expectations (2.14.4)
rspec-mocks (2.14.4)
rspec-rails (2.14.0)
rubygems-bundler (1.4.2)
rvm (1.11.3.8)
sass (3.2.13)
sass-rails (4.0.1)
sdoc (0.3.20)
slop (3.4.7)
spoon (0.0.4)
sprockets (2.10.1)
sprockets-rails (2.0.1)
state_machine (1.2.0)
therubyrhino (2.0.2)
therubyrhino_jar (1.7.4)
thor (0.18.1)
thread_safe (0.1.3 java)
tilt (1.4.1)
timers (2.0.0)
treetop (1.4.15)
turbolinks (2.1.0)
tzinfo (0.3.38)
uglifier (2.4.0)
warden (1.2.3)

**Comment by talbright** [comment]
Are you running bin/setup from the project root or from the bin directory?

**Comment by atulkhaire** [comment]
Hi Trent,

Sorry about that. It was actually using rake and rails from /bin dir rather than rearview/bin. I got that one figured out yesterday but down the line I encountered one more error:

undefined Rearview::User in db/seeds.rb

Also rearview.rb file was generated and I set the 'config.graphite_url' which points to hostedgraphte but not sure what should be the value of 'config.sandbox_exec' ?

I have JRuby 1.7.5 and ruby 1.9.3.

After running foreman start it looks like rearview is started at http://localhost:3000. Can I access the application from my browser? or from remote location using public_ip_address:3000  ?

Thanks for being so considerate .

**Comment by atulkhaire** [comment]
Hi Trent,

This is the complete error message:

Setting up databases...
rearview_production already exists
rake aborted!
uninitialized constant Rearview::User
/opt/rearview-1.0.2/db/seeds.rb:1:in `(root)'
/usr/local/rvm/gems/jruby-1.7.5@rearview/gems/railties-4.0.2/lib/rails/engine.rb:540:in`load_seed'
/usr/local/rvm/gems/jruby-1.7.5@rearview/gems/activerecord-4.0.2/lib/active_record/tasks/database_tasks.rb:154:in `load_seed'
/usr/local/rvm/gems/jruby-1.7.5@rearview/gems/activerecord-4.0.2/lib/active_record/railties/databases.rake:181:in`call'
/usr/local/rvm/gems/jruby-1.7.5@rearview/gems/activerecord-4.0.2/lib/active_record/railties/databases.rake:181:in `(root)'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
D, [2014-01-20T18:45:14.581000 #18688] DEBUG -- : Shutdown completed cleanly

after running foreman start, I can see rearview running on localhost:3000 but when login fails with default credentials ie: user: admin@localhost and password: admin.

I think this is because of the above error.

**Comment by atulkhaire** [comment]
Hi Trent,

Do you have any idea about this error message above ?

**Comment by talbright** [comment]
From the root of the project try this:

```
% bin/rake RAILS_ENV=production db:drop db:create db:migrate db:seed
```

**Comment by atulkhaire** [comment]
This is what I get:

root@atul-Inspiron-N5110:/opt/rearview-1.0.2# bin/rake RAILS_ENV=production db:drop db:create db:migrate db:seed
==  BaseSchema: migrating =====================================================
-- create_table("applications", {:force=>true})
   -> 0.1340s
-- add_index("applications", ["ancestry"], {:name=>"index_applications_on_ancestry"})
   -> 0.1860s
   -> 0 rows
-- add_index("applications", ["user_id"], {:name=>"user_id"})
   -> 0.2010s
   -> 0 rows
-- create_table("job_data", {:force=>true})
   -> 0.1320s
-- create_table("job_errors", {:force=>true})
   -> 0.1220s
-- add_index("job_errors", ["job_id"], {:name=>"job_id"})
   -> 0.2120s
   -> 0 rows
-- create_table("jobs", {:force=>true})
   -> 0.1430s
-- add_index("jobs", ["app_id"], {:name=>"app_id"})
   -> 0.1920s
   -> 0 rows
-- add_index("jobs", ["id", "name"], {:name=>"id_name_version_key", :unique=>true})
   -> 0.1690s
   -> 0 rows
-- add_index("jobs", ["user_id"], {:name=>"jobs_ibfk_1"})
   -> 0.1780s
   -> 0 rows
-- create_table("users", {:force=>true})
   -> 0.1210s
-- add_index("users", ["email"], {:name=>"email", :unique=>true})
   -> 0.2010s
   -> 0 rows
==  BaseSchema: migrated (2.0100s) ============================================

==  AddIndexes: migrating =====================================================
-- add_index(:jobs, :status)
   -> 0.1770s
   -> 0 rows
-- add_index(:job_errors, :status)
   -> 0.1800s
   -> 0 rows
-- add_index(:job_data, :job_id)
   -> 0.1770s
   -> 0 rows
==  AddIndexes: migrated (0.5390s) ============================================

rake aborted!
uninitialized constant Rearview::User
/opt/rearview-1.0.2/db/seeds.rb:1:in `(root)'
/usr/local/rvm/gems/jruby-1.7.5@rearview/gems/railties-4.0.2/lib/rails/engine.rb:540:in`load_seed'
/usr/local/rvm/gems/jruby-1.7.5@rearview/gems/activerecord-4.0.2/lib/active_record/tasks/database_tasks.rb:154:in `load_seed'
/usr/local/rvm/gems/jruby-1.7.5@rearview/gems/activerecord-4.0.2/lib/active_record/railties/databases.rake:181:in`call'
/usr/local/rvm/gems/jruby-1.7.5@rearview/gems/activerecord-4.0.2/lib/active_record/railties/databases.rake:181:in `(root)'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
D, [2014-01-21T14:29:59.616000 #7938] DEBUG -- : Shutdown completed cleanly

**Comment by talbright** [comment]
I downloaded 1.0.2 and couldn't reproduce it. It does look like something in your environment is off. What happens when you run this:

```
$ bin/rails runner -e production db/seeds.rb
```

**Comment by atulkhaire** [comment]
I am not sure what I am missing here. Here's the output I get

root@atul-Inspiron-N5110:/opt/rearview-1.0.2# bin/rails runner -e production db/seeds.rb
NameError: uninitialized constant Rearview::User
D, [2014-01-21T14:45:38.219000 #8697] DEBUG -- : Shutdown completed cleanly

**Comment by atulkhaire** [comment]
These are my environment variables:

GRAPHITE_REFRESH=60000
rvm_bin_path=/usr/local/rvm/bin
GEM_HOME=/usr/local/rvm/gems/jruby-1.7.5@rearview
SHELL=/bin/bash
TERM=xterm
IRBRC=/usr/local/rvm/rubies/jruby-1.7.5/.irbrc
OLDPWD=/opt/test
MY_RUBY_HOME=/usr/local/rvm/rubies/jruby-1.7.5
USER=root
SMTP_PORT=25
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:_.tar=01;31:_.tgz=01;31:_.arj=01;31:_.taz=01;31:_.lzh=01;31:_.lzma=01;31:_.tlz=01;31:_.txz=01;31:_.zip=01;31:_.z=01;31:_.Z=01;31:_.dz=01;31:_.gz=01;31:_.lz=01;31:_.xz=01;31:_.bz2=01;31:_.bz=01;31:_.tbz=01;31:_.tbz2=01;31:_.tz=01;31:_.deb=01;31:_.rpm=01;31:_.jar=01;31:_.war=01;31:_.ear=01;31:_.sar=01;31:_.rar=01;31:_.ace=01;31:_.zoo=01;31:_.cpio=01;31:_.7z=01;31:_.rz=01;31:_.jpg=01;35:_.jpeg=01;35:_.gif=01;35:_.bmp=01;35:_.pbm=01;35:_.pgm=01;35:_.ppm=01;35:_.tga=01;35:_.xbm=01;35:_.xpm=01;35:_.tif=01;35:_.tiff=01;35:_.png=01;35:_.svg=01;35:_.svgz=01;35:_.mng=01;35:_.pcx=01;35:_.mov=01;35:_.mpg=01;35:_.mpeg=01;35:_.m2v=01;35:_.mkv=01;35:_.webm=01;35:_.ogm=01;35:_.mp4=01;35:_.m4v=01;35:_.mp4v=01;35:_.vob=01;35:_.qt=01;35:_.nuv=01;35:_.wmv=01;35:_.asf=01;35:_.rm=01;35:_.rmvb=01;35:_.flc=01;35:_.avi=01;35:_.fli=01;35:_.flv=01;35:_.gl=01;35:_.dl=01;35:_.xcf=01;35:_.xwd=01;35:_.yuv=01;35:_.cgm=01;35:_.emf=01;35:_.axv=01;35:_.anx=01;35:_.ogv=01;35:_.ogx=01;35:_.aac=00;36:_.au=00;36:_.flac=00;36:_.mid=00;36:_.midi=00;36:_.mka=00;36:_.mp3=00;36:_.mpc=00;36:_.ogg=00;36:_.ra=00;36:_.wav=00;36:_.axa=00;36:_.oga=00;36:_.spx=00;36:_.xspf=00;36:
_system_type=Linux
SMTP_USERNAME=xyz
SUDO_USER=root
SUDO_UID=0
rvm_path=/usr/local/rvm
SMTP_PASSWORD=xyz
USERNAME=root
rvm_prefix=/usr/local
MAIL=/var/mail/root
PATH=/usr/local/rvm/gems/jruby-1.7.5@rearview/bin:/usr/local/rvm/gems/jruby-1.7.5@global/bin:/usr/local/rvm/rubies/jruby-1.7.5/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/opt/test/rearview-1.0.2
LANG=en_US.UTF-8
SMTP_HOST=xyz
_system_arch=x86_64
SMTP_PROTOCOL=smtp
SMTP_FROM=xyz@ab.com
_system_version=12.04
rvm_version=1.25.15 (stable)
SHLVL=1
SUDO_COMMAND=/bin/bash
HOME=/home/atul
rvm_ruby_string=jruby-1.7.5
LOGNAME=root
GEM_PATH=/usr/local/rvm/gems/jruby-1.7.5@rearview:/usr/local/rvm/gems/jruby-1.7.5@global
GRAPHITE_URL=https://www.hostedgraphite.com/xyz../abc..-abc..-uvw../graphite
LESSOPEN=| /usr/bin/lesspipe %s
rvm_delete_flag=0
SUDO_GID=0
DISPLAY=:0
RUBY_VERSION=jruby-1.7.5
LESSCLOSE=/usr/bin/lesspipe %s %s
_system_name=Ubuntu
COLORTERM=gnome-terminal
XAUTHORITY=/home/atul/.Xauthority
_=/usr/bin/env

I tried both rearview-1.0.2.zip and rearview-1.0.2.tar.gz.

**Comment by talbright** [comment]
Unfortunately I'm a bit stuck. It looks ok and is very similar to what I have, particularly looking at GEM_PATH and GEM_HOME they all look right.
