### ISSUE TITLE
database setup fails

### ISSUE THREAD

**Issue by grimm26** [livingsocial/rearview#19]
I'm using postgres 9.1 as my database:
/bin/setup
....
Setting up databases...
==  BaseSchema: migrating =====================================================
-- create_table("applications", {:force=>true})
   -> 0.0220s
-- add_index("applications", ["ancestry"], {:name=>"index_applications_on_ancestry"})
   -> 0.0060s
   -> 0 rows
-- add_index("applications", ["user_id"], {:name=>"user_id"})
   -> 0.0190s
   -> 0 rows
-- create_table("job_data", {:force=>true})
rake aborted!
An error has occurred, this and all later migrations canceled:

The limit on text can be at most 1GB - 1byte./home/rearview/.rvm/gems/jruby-1.7.10/gems/activerecord-jdbc-adapter-1.3.4
/lib/arjdbc/postgresql/adapter.rb:126:in `type_to_sql'

**Comment by grimm26** [comment]
Found that it is because the schema sets text columns with a limit of 2147483647 which is too large.  I changed the limits to 1073741823 (half of the original) and now setup completes.

**Comment by talbright** [comment]
This must be a portability problem between mysql (which is what we are using) and postgres and the way ActiveRecord generated that. I do think 1GB should be enough, though theoretically you could pull enough data from graphite to exceed even that. I don't like the idea of going back and editing an existing migration, but postgres is a popular (for good reasons) RDBMS, so I want to make sure we support it adequately.

**Comment by grimm26** [comment]
I'm hoping that there would not be 1GB of data in a single record :)

**Comment by talbright** [comment]
You can choose a large date range for your monitor, and collect stats from multiple metrics in one monitor. There shouldn't be but as I said it is theoretically possible. Lots of bad things would probably happen though with your JVM, so having a text field of "only" 1GB would be the least of the issues. We do have a ticket internally to work on preventing this kind of overflow, but haven't gotten to it yet.

**Comment by talbright** [comment]
Just confirmed in the docs for [postgresql](http://www.postgresql.org/docs/current/interactive/datatype-character.html)

The longest possible character string that can be stored is about 1 GB

And in [MySQL](http://dev.mysql.com/doc/refman/5.0/en/storage-requirements.html) long text has to be less than 2 ^ 32 (4GB).

I'll make the same change you did, editing the migration and changing the limit to 1073741823.
