### ISSUE TITLE
bin/rails fails

### ISSUE THREAD

**Issue by grimm26** [livingsocial/rearview#20]
When running bin/setup, the run_install() function runs /bin/rails which throws this error:

D, [2014-01-23T16:30:17.141000 #32698] DEBUG -- : Shutdown completed cleanly
LoadError: load error: /home/rearview/rearview-1.1.1/config/environment -- java.lang.NoSuchFieldException: isRestricted
               require at org/jruby/RubyKernel.java:1083
               require at /home/rearview/.rvm/gems/jruby-1.7.10/gems/activesupport-4.0.2/lib/active_support/dependencie
s.rb:229
       load_dependency at /home/rearview/.rvm/gems/jruby-1.7.10/gems/activesupport-4.0.2/lib/active_support/dependencie
s.rb:214
               require at /home/rearview/.rvm/gems/jruby-1.7.10/gems/activesupport-4.0.2/lib/active_support/dependencie
s.rb:229
  require_environment! at /home/rearview/.rvm/gems/jruby-1.7.10/gems/railties-4.0.2/lib/rails/application.rb:189
                (root) at /home/rearview/.rvm/gems/jruby-1.7.10/gems/railties-4.0.2/lib/rails/commands.rb:44
               require at org/jruby/RubyKernel.java:1083
                (root) at bin/rails:12
D, [2014-01-23T16:30:45.149000 #32717] DEBUG -- : Shutdown completed cleanly

**Comment by talbright** [comment]
I think I know what the problem here is. Could you completely comment out https://github.com/livingsocial/rearview/blob/master/config/initializers/unlimited_strength_cryptography.rb and try it again? You'll get another exception which you can resolve if you follow the steps I mentioned in issue #17.

**Comment by atulkhaire** [comment]
In bin/setup script under run_install function change /bin/rails to bin/rails. It should use rails from rearview/bin directory not /bin directory.

**Comment by grimm26** [comment]
swapsjd, /bin/rails was a typo on my part.

talbright, I commented out the entire contents of unlimited_strength_cryptography.rb and I do not get the exception mention in [#17](https://github.com/livingsocial/rearview/issues/17).  I get:

```
D, [2014-01-24T09:41:27.214000 #1489] DEBUG -- : Shutdown completed cleanly
LoadError: load error: /home/rearview/rearview-1.1.1/config/environment -- java.lang.NoSuchFieldExcep
tion: isRestricted
               require at org/jruby/RubyKernel.java:1083
               require at /home/rearview/.rvm/gems/jruby-1.7.10/gems/activesupport-4.0.2/lib/active_s
upport/dependencies.rb:229
       load_dependency at /home/rearview/.rvm/gems/jruby-1.7.10/gems/activesupport-4.0.2/lib/active_s
upport/dependencies.rb:214
               require at /home/rearview/.rvm/gems/jruby-1.7.10/gems/activesupport-4.0.2/lib/active_s
upport/dependencies.rb:229
  require_environment! at /home/rearview/.rvm/gems/jruby-1.7.10/gems/railties-4.0.2/lib/rails/applica
tion.rb:189
                (root) at /home/rearview/.rvm/gems/jruby-1.7.10/gems/railties-4.0.2/lib/rails/command
s.rb:44
               require at org/jruby/RubyKernel.java:1083
                (root) at bin/rails:12
D, [2014-01-24T09:41:55.225000 #1506] DEBUG -- : Shutdown completed cleanly
```

**Comment by talbright** [comment]
Ok looks like I left the exact same initializer in rearview-engine, minus the rescue block. Ughh.

I'll clean this up and roll-out a new release this afternoon.

**Comment by grimm26** [comment]
perhaps another thing worth mentioning is that I am on debian squeeze using openjdk

```
# java -version
java version "1.6.0_27"
OpenJDK Runtime Environment (IcedTea6 1.12.6) (6b27-1.12.6-1~deb6u1)
OpenJDK 64-Bit Server VM (build 20.0-b12, mixed mode)
```

**Comment by talbright** [comment]
Yeah if you were using 1.7.x this error would not occur, but as I mentioned above its more or less a bug on my part.

**Comment by grimm26** [comment]
Removing all of the lines from that file does not change my error.

**Comment by talbright** [comment]
Did you download the latest? https://github.com/livingsocial/rearview/archive/v1.1.2.zip

**Comment by grimm26** [comment]
Ah, all good (after porting the pg text limit fix).  Thanks.

**Comment by talbright** [comment]
Cool. The fix for the pg text limit is in master but not in an official release yet.
