### ISSUE TITLE
Rearview-Scala version unable to send email on alerts

### ISSUE THREAD

**Issue by atulkhaire** [livingsocial/rearview#21]
Hi,

I have setup rearview-scala version on EC2 instance and using Amazon SES.

In the conf/common.conf file I have updated values as follows:

statsd.enabled=false
graphite.host="https://hostedgraphite.com/acces-key"

email.from="bxyz@zb.com"
email.host="email-smtp.us-east-1.amazonaws.com"
email.port=465
email.user="xyz"
email.password="abc"
alert.class_names = ["rearview.alert.LiveEmailAlert"]

with these configs rearview does not send emails on alerts. I tried on both ports i.e 25 and 465. Even telnet to email-smtp.us-east-1.amazonaws.com 465 was successful. 

Am I missing anything ?

**Comment by talbright** [comment]
Unfortunately, the scala version is unsupported. I've re-tagged some things, and created a branch and updated the README.md file in that branch to call this out more clearly.
