### ISSUE TITLE
Monitor output window error - not finding i18n version 0.6.5

### ISSUE THREAD

**Issue by boks1971** [livingsocial/rearview#26]
Before I file the bug, have to admit I am a novice Ruby user and quite possibly this is a user error:-)

Installed rearview-1.1.2 on Ubuntu 12.04 using the setup procedure described in the project

When I add a monitor and test it, I get the following error in output window

---

/home/boks/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.5.2/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find i18n-0.6.5 in any of the sources (Bundler::GemNotFound)
    from /home/boks/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.5.2/lib/bundler/spec_set.rb:85:in`map!'
    from /home/boks/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.5.2/lib/bundler/spec_set.rb:85:in `materialize'
    from /home/boks/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.5.2/lib/bundler/definition.rb:133:in`specs'
    from /home/boks/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.5.2/lib/bundler/definition.rb:178:in `specs_for'
    from /home/boks/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.5.2/lib/bundler/definition.rb:167:in`requested_specs'
    from /home/boks/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.5.2/lib/bundler/environment.rb:18:in `requested_specs'
    from /home/boks/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.5.2/lib/bundler/runtime.rb:13:in`setup'
    from /home/boks/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.5.2/lib/bundler.rb:119:in `setup'
    from /home/boks/workspace/rearview/rearview-1.1.2/sandbox/monitor_script20140130-27375-1r4o78l:10:in`<main>'

---

My gem list is

---

**\* LOCAL GEMS ***

actionmailer (4.0.2)
actionpack (4.0.2)
activemodel (4.0.2)
activerecord (4.0.2)
activerecord-deprecated_finders (1.0.3)
activerecord-jdbc-adapter (1.3.4)
activerecord-jdbcmysql-adapter (1.3.4)
activesupport (4.0.2)
ancestry (2.0.0)
arel (4.0.1)
atomic (1.1.14 java)
bcrypt-ruby (3.1.2 java)
bouncy-castle-java (1.5.0147)
broach (0.3.0)
builder (3.1.4)
bundler (1.5.2)
bundler-unload (1.0.2)
celluloid (0.14.1)
coderay (1.1.0)
coffee-rails (4.0.1)
coffee-script (2.2.0)
coffee-script-source (1.6.3)
devise (3.2.2)
diff-lcs (1.2.5)
dotenv (0.9.0)
erubis (2.7.0)
execjs (2.0.2)
executable-hooks (1.3.1)
faraday (0.8.8)
ffi (1.9.3 java)
foreman (0.63.0 java)
gem-wrappers (1.2.4)
hashie (2.0.5)
hike (1.2.3)
hitimes (1.2.1 java)
httparty (0.12.0)
httpauth (0.2.0)
i18n (0.6.9)
jbuilder (1.5.3)
jdbc-mysql (5.1.27)
jquery-rails (3.0.4)
jruby-launcher (1.0.19 java)
jruby-openssl (0.9.4)
json (1.8.1 java)
jwt (0.1.8)
mail (2.5.4)
method_source (0.8.2)
mime-types (1.25.1)
minitest (4.7.5)
multi_json (1.8.2)
multi_xml (0.5.5)
multipart-post (1.2.0)
nap (0.6.0)
oauth2 (0.8.1)
omniauth (1.1.4)
omniauth-google-oauth2 (0.2.1)
omniauth-oauth2 (1.1.1)
orm_adapter (0.5.0)
polyglot (0.3.3)
protected_attributes (1.0.5)
pry (0.9.12.4 java)
puma (2.7.1 java)
rack (1.5.2)
rack-test (0.6.2)
rails (4.0.2)
railties (4.0.2)
rake (10.1.1)
rdoc (3.12.2)
rearview (1.1.2 jruby)
rspec-core (2.14.7)
rspec-expectations (2.14.4)
rspec-mocks (2.14.4)
rspec-rails (2.14.0)
rubygems-bundler (1.4.2)
rvm (1.11.3.8)
sass (3.2.13)
sass-rails (4.0.1)
sdoc (0.3.20)
slop (3.4.7)
spoon (0.0.4)
sprockets (2.10.1)
sprockets-rails (2.0.1)
state_machine (1.2.0)
statsd-ruby (1.2.1)
therubyrhino (2.0.2)
therubyrhino_jar (1.7.4)
thor (0.18.1)
thread_safe (0.1.3 java)
tilt (1.4.1)
timers (2.0.0)
treetop (1.4.15)
turbolinks (2.1.0)
tzinfo (0.3.38)
uglifier (2.4.0)
warden (1.2.3)

---

Will appreciate any help understanding this issue

**Comment by atulkhaire** [comment]
What does your config.sandbox_exec look like ?

If you have changed it, then change it back to 
config.sandbox_exec = ["rvm-exec","ruby-1.9.3@rearview-sandbox","ruby"].

before running foreman start do the below steps in the order specified, from rearview's root directory.

1) 'rvm use ruby-1.9.3'
2) 'cd sandbox'
3) 'bundle install' and then go back to rearview's root directory. 
4) 'rvm use jruby-1.7.5' (if you have installed jruby-1.7.5) or 'rvm use jruby'
5) foreman start.

Now perform your monitor test.

**Comment by boks1971** [comment]
Thank you very much for your help.

I had changed the config.sandbox_exec setting. It is as you have mentioned above
config.sandbox_exec = ["rvm-exec","ruby-1.9.3@rearview-sandbox","ruby"]

After I did the sequence of steps you mentioned, I am not seeing that error any more. Thank you once again!!
