### ISSUE TITLE
Time zone in the UI

### ISSUE THREAD

**Issue by mike-yesware** [livingsocial/rearview#3]
My server is set to UTC and that's what I'm getting for times in the Rearview UI. I'd prefer to not change the server time if I don't have to. Is there a way to tell Rearview which timezone to display in and run scheduled jobs at?

**Comment by steveakers** [comment]
Everything in Rearview is in UTC. We have on a long list of suggested features the ability to display timestamps in the user's timezone, but it has never been high enough priority. We've found it easier just to always think in terms of UTC. Having said that, I would love it if someone had the time to submit that change. :)

**Comment by mike-yesware** [comment]
Well... along those line, I think read somewhere that there was a Ruby port in the works? Did that ever materialize? I ask because I have zero experience in Scala (or Java, for that matter), so hacking on the project is a much bigger investment than I think I can make.

**Comment by steveakers** [comment]
It is! In fact, we hope to have it out next week.

**Comment by mike-yesware** [comment]
(facepalm). I just spent more time than I'd care to admit getting a Chef recipe put together for compiling and running this version :smile:.

I'm looking forward to it though!

**Comment by mike-yesware** [comment]
Hey @steveakers. How's the Ruby port looking?

**Comment by talbright** [comment]
It's looking pretty good. I released it internally here at LivingSocial into production last week. There's been a few kinks here and there we are still working out, but overall its running fairly well. We have on our roadmap to open source the project sooner rather than later, but I don't have a specific date yet.

I should also mention that its technically JRuby not Ruby. We needed the power of the native threading you get on the JVM platform.

**Comment by mike-yesware** [comment]
If you aim for sooner, you might have another contributor on your hands here :) There's some things I'd like to see (HipChat integration for starters) that I'm not likely to add to the Play version.

Thanks for a great app!

**Comment by steveakers** [comment]
I'm very excited about this version. If nothing else than the potential for more contributors! We've also used this opportunity to fix a few things plus add some additional features. I'm also excited about what's coming next. :)

**Comment by talbright** [comment]
There's a decent (but not perfect) extension point for easily adding new alert types. One of the developers here added support for Campfire.
