### ISSUE TITLE
Alerts getting delivered at an interval of 60 minutes.

### ISSUE THREAD

**Issue by atulkhaire** [livingsocial/rearview#31]
Hi,

Rearview is sending email alerts after every 60 minutes even if monitors are triggered every 5 minutes or any other interval for that matter. 

My graphite server is in Pacific time zone and because of that I made smal changes in the 'create_from_to_dates' function in monitor_runner.rb file. 
This is how it looks.

 def create_from_to_dates(minutes = nil, to_date = nil)
        logger.debug "#{self}#create_from_to_dates minutes:#{minutes} to_date:#{to_date}"
        graphite_date_format = '%H:%M_%Y%m%d'
        incoming_date_format = '%m/%d/%Y %H:%M'
        mins = minutes.nil? ? @@DEFAULT_MINUTES : minutes.to_i
        if to_date == "now" || to_date.nil?
          local = DateTime.now
          pacific_offset = Rational(-6,24)
          now = local.new_offset(pacific_offset)
        else
          now = DateTime.strptime(to_date, incoming_date_format)
          pacific_offset = Rational(-6,24)
          now = now.new_offset(pacific_offset)
        end
        to = (now - 10.minutes).strftime(graphite_date_format)
        from = (now - (mins + 15).minutes).strftime(graphite_date_format)
        logger.debug "#{self}#create_from_to_dates from:#{from} to:#{to}"
        [from,to]
      end

This is the only change I made.

I spent a lot of time digging into this but did not had any luck. Do you know what might be the reason for this ?

In order to interact with Pacific time zone is there any other place where I need to make any changes ?

Thanks in advance.

**Comment by talbright** [comment]
By design Rearview will only alert every 60 minutes to prevent alert floods. There's a setting, on a per job basis, that can be used to tweak this. However, that setting is not exposed in the UI so you would need to edit it manually in the database. Take a look at **job.error_timeout**.

What did you end up having to set for your pagerduty url to in issue #25?

**Comment by talbright** [comment]
You can look at issue #24 for some comments about time zone support. Also, some date calculations are done in the job_error model and in the UI there is obvioulsy some sensitivity to TZ. I can't say for sure on the UI front what if anything needs to be done. I just recently took that part over.

Of course a good solution for this in a PR would be welcome.
