### ISSUE TITLE
Is there a way to interact with database from the monitor scripts ?

### ISSUE THREAD

**Issue by atulkhaire** [livingsocial/rearview#33]
Hi,

I want to use some simple sql queries such as create, insert, update, select etc from monitor scripts. I am planning to perform these operations on a mysql database used by rearview i.e (database mentioned in database.yml). Mysql is installed on the same box as reaview. 

Is it possible to interact with database from monitor scripts ?  If not is there any other way to achieve this ?

Thanks

**Comment by talbright** [comment]
Rearview monitor scripts are specifically meant to pull and analyze data from graphite. We are not trying to provide a general monitoring framework such as Nagios does. That being said, if you can get the data to graphite you can monitor it. We use statsd on the backend, and statsd-ruby to send metrics we want to monitor, from whatever relevant code. Cron jobs, Rails apps, Resque workers, etc

Also, monitor scripts run in a sandbox with a $SAFELEVEL = 3 to prevent malicious scripts from being able to access resources such as database connections.

**Comment by atulkhaire** [comment]
Hi,

The reason I asked this question was because I am looking for setting up monitors which will check 'uptime' and 'downtime' of a service. Definitions are below.

Downtime:  The number of minutes in a month in which the Response Time of the service is above the threshold. 
Uptime:  The total number of minutes in a month minus the number of minutes of Downtime in a month, then divided by the total number of minutes in a month.

I thought this could be achieved by bringing database into play. For example whenever a target metric (Response time) would exceed threshold value I would update the count in a database table and then at the end of each month the count values from the database will be checked for 'Uptime' and 'Downtime'.

But since monitors scripts run in sandbox I cannot go ahead with this approach. So is there a way rearview can help me achieve this ?
