### ISSUE TITLE
Default alert URI not working

### ISSUE THREAD

**Issue by shamil** [livingsocial/rearview#35]
Probably I misunderstood something, but why I need those default alert URI if it not used? Alerts are never sent using the data from default alert URIs, no?

**Comment by talbright** [comment]
Assuming you are talking about this setting:

![settings-view](https://cloud.githubusercontent.com/assets/212177/2598704/a29701de-bacd-11e3-83c6-2790bd7e2b1d.png)

Once you set a default value, it will automatically populate any _new_ monitor you create. I can see that you expected it to become the default value for all existing monitors, but that is not the case.

![add-view](https://cloud.githubusercontent.com/assets/212177/2598723/17e7656e-bace-11e3-8bde-138d4f4e977e.png)

**Comment by shamil** [comment]
I understand. Thanks
