### ISSUE TITLE
Sandbox permissions on monitor scripts.

### ISSUE THREAD

**Issue by gdavis33** [livingsocial/rearview#37]
The simple operation of
puts @a.values.sum

Creates this error.

/opt/rearview/rearview/sandbox/monitor_script20140419-4332-1fd20qm:206:in `write': Insecure operation - write (SecurityError)
    from /opt/rearview/rearview/sandbox/monitor_script20140419-4332-1fd20qm:206:in`puts'
    from /opt/rearview/rearview/sandbox/monitor_script20140419-4332-1fd20qm:206:in `puts'
    from /opt/rearview/rearview/sandbox/monitor_script20140419-4332-1fd20qm:206:in`block in scoped_eval'

puts @a or puts @timeseries seems to work just fine.

**Comment by shamil** [comment]
I had this also, it happens if the value you try to print **float** type. I think this is a bug in ruby.
Try `puts @a.values.sum.to_i` What version of ruby do you use?

**Comment by gdavis33** [comment]
Yup, that was it. Thanks for the quick response, that was driving me nuts! The sandbox runs ruby-1.9.3-p545 I think. I had some other odd issues when I tried different versions so I just went with tested versions of ruby/jruby. I would also add that I'm a ruby newbie.

**Comment by shamil** [comment]
I would try to use some ruby version manager like [chruby](https://github.com/postmodern/chruby) and try couple of different versions. I'm using latest stable 2.1.1 and all seems to work properly

**Comment by gdavis33** [comment]
Ok, I've updated to rvm, jruby-1.7.12 ruby-2.1.1. Everything now seems to work correctly in terms of the sandbox environment. That said, the wiki docs suggest that there are a few variables provided to the monitor and some like a-z and timeseries work but I have been unable to use the name variable with any success. As a result there is no way from me to differentiate alerts from a set of monitors checking the same or similar metrics on different sources. I should be able to use the monitor name in the raised exception no?

**Comment by talbright** [comment]
If one of the variables doesn't seem to be working, can you please create a separate issue for that? In the meantime you could of course do something like this to differentiate:

raise "my monitor name: blah blah blah blah"

**Comment by gdavis33** [comment]
Sorry. I'll close this one and move to a new issue. Thanks.
