### ISSUE TITLE
Bundle installed problems

### ISSUE THREAD

**Issue by martinyeh** [livingsocial/rearview#38]
bundle install
Gemfile syntax error compile error
on line 44: syntax error, unexpected ':', expecting kEND
  gem 'sdoc', require: false
                      ^
how to resolve this problem?

**Comment by cflipse** [comment]
Make sure you're using the right version of Ruby.  The syntax error is triggering because the Gemfile is using some 1.9-and-later syntax, and you're running bundler with a 1.8.x ruby.

**Comment by martinyeh** [comment]
I installed RVM to help me manage the new version of ruby. The problems seem solved but got other problems now:

Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
(in /home/csiuser/rearview)
rake aborted!
Don't know how to build task 'rearview:setup'
/home/csiuser/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
/home/csiuser/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in`<main>'
(See full trace by running task with --trace)

**Comment by talbright** [comment]
Did you get past this?

This has come up a couple of times with other users. You can see in your output above that you are still not using Jruby.

```
/home/csiuser/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in eval' /home/csiuser/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in'
```
