### ISSUE TITLE
Rearview does not allow selecting multiple series with `{...}`

### ISSUE THREAD

**Issue by shawnjgoff** [livingsocial/rearview#42]
Graphite allows selecting multiple series using `{...}`. A useful example of this syntax is given in the documentation for the [averageSeriesWithWildcards function](http://graphite.readthedocs.org/en/0.9.10/functions.html#graphite.render.functions.averageSeriesWithWildcards)

When trying to use this syntax in Rearview, it shows a flash that says "Metrics contains an invalid metric".

**Comment by shawnjgoff** [comment]
The [group function](http://graphite.readthedocs.org/en/0.9.10/functions.html#graphite.render.functions.group) can be used as a workaround.

**Comment by talbright** [comment]
I'm pretty sure I know the issue, sounds like a bug in the parser I wrote. Would you mind cutting and pasting the complete syntax you used?

**Comment by shawnjgoff** [comment]
`sumSeries(server.app1.memory.memory.{buffered,cached,free})`

**Comment by talbright** [comment]
Thought so, I know the problem. I'll work with @steveakers to get a fix in for this.

**Comment by talbright** [comment]
@shawnjgoff you can update your gemfile to get the update:

``` ruby
 gem 'rearview', '1.2.2.rc.1'
```
