### ISSUE TITLE
Running in "production" ?

### ISSUE THREAD

**Issue by johntdyer** [livingsocial/rearview#5]
Hello,

  This product looks great, thanks so much for open sourcing it .  I want to deploy this for a few members of my team to play with, but I am not sure how best to deploy it.   is the `./sbc start` recommended just for development or is that fine for a staging deployment for my team ?  Sorry if this is a dumb question, I am just not very familiar w/ Scala so I wanted to make sure my team gets the best experience 

Thanks

-John

**Comment by pauldegoes** [comment]
John,

Glad to know rearview can be of use to you.

``` scala
 ./sbt start 
```

Is the standard way to start the apps in production.

**Comment by johntdyer** [comment]
Awesome, thanks !
