### ISSUE TITLE
common.conf not updateing

### ISSUE THREAD

**Issue by johntdyer** [livingsocial/rearview#6]
So I am trying to make a chance to the graphite host in my common.conf directory but it doesn't seem to be taking effect.  

In my conf I have

``` properties
# Graphite
graphite.host="http://graphite-internal.int.xxxxx.com"
graphite.auth=""
graphite.timeout=10000
```

but you can see in the debug logs its still trying the other hostname. 

``` shell
[debug] s.s.c.FixRowNumberOrdering - No row numbers to fix
[debug] s.s.c.QueryCompiler - After phase fixRowNumberOrdering: (no change)
[debug] s.s.s.BaseSession - Preparing statement: select s4.`id`, s4.`user_id`, s4.`app_id`, s4.`name`, s4.`cron_expr`, s4.`metrics`, s4.`monitor_expr`, s4.`minutes`, s4.`to_date`, s4.`description`, s4.`active`, s4.`status`, s4.`last_run`, s4.`next_run`, s4.`alert_keys`, s4.`error_timeout`, s4.`created`, s4.`modified`, s4.`deleted_at` from `jobs` s4 where (s4.`deleted_at` is null) and (s4.`active` = true)
[info] play - Application started (Prod)
[info] play - Listening for HTTP on /0.0.0.0:9000
[info] a.e.s.Slf4jEventHandler - Slf4jEventHandler started
[error] application - Graphite request failure: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Authorization Required</title>
</head><body>
<h1>Authorization Required</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
<hr>
<address>Apache Server at graphite.int.xxxxx.com Port 443</address>
</body></html>
```

I have tried killing the process, which didnt work.  I also tried re-running `./sbt test` to see if that maybe would help, but no dice so far.  How do I do things like update the config, and reload config ? 

Thanks!

-John

**Comment by steveakers** [comment]
Try adding ":8080" at the end of the hostname:

```
graphite.host="http://graphite-internal.int.xxxxx.com:8080"
```

**Comment by johntdyer** [comment]
both hosts are correct, the problem is that its not picking up the new config at all... 

graphite.host="https://graphite-internal.int.xxxxx.com"

vs 

graphite.host="https://graphite.int.xxxxx.com"

**Comment by steveakers** [comment]
What do you mean by new config? Do you mean common.conf used to have graphite.int.xxxxx.com and then you changed it to graphite-internal.in.xxxxx.com? If so, did you kill rearview and restarted it after the change?

**Comment by steveakers** [comment]
I just tried running the scala version with one graphite host, changed it to another, quit rearview, and restarted with ./sbt start and it worked. If that didn't work for you you might want to see if there are any java processes running and kill them as well.

**Comment by johntdyer** [comment]
@steveakers - Yes, killed all the processes  `ps aux | grep jav[a]` and nothing.  Then

Grep -R xxxxxx.com /opt/rearview and saw no instances of the host graphite hostname.  I then run `sbt start` and every time I end up w/ the old hostname... sorta driving me nuts at this point :) 

http://note.io/1aJbrQj

**Comment by johntdyer** [comment]
Damn... I am a moron.... My graphite server was redirecting http to https, and that redirect had the old hostname.  Sorry for wasting your time :)
