### ISSUE TITLE
statsd integration

### ISSUE THREAD

**Issue by johntdyer** [livingsocial/rearview#7]
Hey guys, 

 How does statsd used with the product?  I see this in the logs with it disabled

`
[warn] application - Send will be NOOP because statsd.enabled is not enabled
`

Since I dont use stats I am not sure what this actually means...

**Comment by steveakers** [comment]
Rearview does log its own stats into graphite via statsd (job status, schedule status, etc.)

**Comment by johntdyer** [comment]
ah, ok. That makes sense.   I was asking because email doesn't seem to be working for me.  I set the following

```
# Email
email.from="donotreply@tropo.com"
email.host="smtp.gmail.com"
email.port=587
email.user="donotreply@tropo.com"
email.password="xxxxxx"
```

and then in the UI I added an email address when the alert is triggered ( http://note.io/1h5SLlg ).  I can see in the logs that it's "alerting" but I am not getting any email.   I also ran tcpdump looking for traffic on 587, but I dont see any.   That makes me thing rearview is not actually sending anything...   I can open another ticket on this if want.  Thanks again !

**Comment by steveakers** [comment]
Have you tried port 465? Sorry, I'm not a scala guy either and the one who built rearview is at another startup. Our current version is Ruby. We hope to open source it soon.

**Comment by johntdyer** [comment]
Yea, no change on 465... Any rough ETA on when your ruby version might 
be open sourced?

**Comment by johntdyer** [comment]
@steveakers - Any chance u can give me some idea of when u guys may open source that product ? I am extremely interested in it :)

**Comment by steveakers** [comment]
Sorry... the Ruby version will be open sourced by the end of the month. We have one more functionality related sprint we want to complete before the open sourcing sprint. I can't wait to get it out there so folks can start using and contributing!

**Comment by johntdyer** [comment]
Great, so glad to hear this !

**Comment by Oscil8** [comment]
Any updates on the progress of the Ruby version?

**Comment by talbright** [comment]
Yup...it's coming along and we are actively working on it -- but we aren't there yet. We decided to upgrade the project to Rails 4.0, and with the way apps are deployed and managed internally, it really made sense for us to convert it to a rails engine. This weekend I hit a road bump I'm still working through with getting the devise/oauth2 working correctly in a rails engine.

**Comment by talbright** [comment]
I'm still working out some kinks over the holidays, but you can see the progress here: https://github.com/livingsocial/rearview/tree/ruby-port
